name: Build and Deploy Next.js App to K3s

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: nextjs-app
      IMAGE_TAG: build-${{ github.run_number }}
      IMAGE_FILE: nextjs-app.tar

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Save Docker image to tar
        run: |
          docker save $IMAGE_NAME:$IMAGE_TAG -o $IMAGE_FILE

      - name: Fix permissions for tar
        run: chmod 644 ${{ github.workspace }}/nextjs-app.tar

      - name: Copy image to VPS
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "${{ github.workspace }}/nextjs-app.tar"
          target: "/home/deployer/frontend"

      - name: Deploy on VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
            ctr -n k8s.io images import /home/deployer/frontend/nextjs-app.tar
            cd /home/deployer/frontend
            k3s kubectl set image deployment wt-frontend-deployment react-container=nextjs-app:${{ env.IMAGE_TAG }} -n default || k3s kubectl apply -f deployment.yaml
            kubectl rollout restart deployment wt-frontend-deployment 